### ISSUE TITLE
Adding Support for Cycles

### ISSUE THREAD

**Issue by adamnovak** [jltsiren/gcsa2#1]
I'm looking to replace the graph indexing code in my string-to-graph aligner that lives over in adamnovak/sequencegraphs. @ekg recommended I look at this project.

My current codebase uses an approach based on keeping a plain string BWT index of several paths through the graph, and then searching in that collection of paths. This provides a modicum of support for cyclic graphs, which I need, for example, in order to be able to find sequences covering the endpoints of inversions or translocations in the index.

I would need some similar partial support for cyclic graphs in GCSA2. What is the state with respect to cyclic graphs so far? Are cycles merely not indexed, or will they break the indexer if they are present? I note that you plan to add cycle support; how are you planning to design that? What constraints (i.e. only going around a cycle once) would you plan to impose? Would it be possible for me to contribute to that part of the project, in order to get it working for my aligner?

**Comment by jltsiren** [comment]
The implementation almost supported cyclic graphs from the beginning. The main construction algorithm already uses a GCSA for a de Bruijn graph to generate the edges, so the index itself definitely supports cyclic graphs.

The only issue I was aware of was a convention inherited from the original GCSA. If the label of a path is unique, I set `to = from` to mark that the path no longer needs to be extended. Because the `to` node is actually a node following the end of the path, `to == from` would denote an empty path in an acyclic graph, and no actual empty paths are used during construction. In a cyclic graph, `to == from` could also mean a cycle, so the convention no longer works.

I changed the convention to `to == -1`, so GCSA now supports cyclic graphs, at least technically. Because the implementation doesn't index paths longer than 128 nodes at the moment, there are no fundamental limits on indexing cycles. The only real constraint is combinatorial. Short cycles can contribute to the combinatorial explosion by creating a lot of branching in a small area.
