### ISSUE TITLE
pre-subsampling results from locate

### ISSUE THREAD

**Issue by ekg** [jltsiren/gcsa2#34]
In some cases it's helpful to get a small subset of exact matches for a given gcsa range even when there are a very large number of matches. However, it can be problematic to actually complete the locate call and fill out the set of hits. Could there be a simple way to obtain a subset that isn't simply the first N such hits?

**Comment by jltsiren** [comment]
Should the subset be random or deterministic?

**Comment by jltsiren** [comment]
GCSA now has the following function:

```
void locate(range_type range, size_type max_positions, std::vector<node_type>& results) const
```

It returns at most `max_positions` occurrences. If `max_positions` is at least 50% of total occurrences, the function locates everything and returns a random subset. Otherwise it keeps trying random positions within the query range until it has found enough distinct occurrences. The algorithm is deterministic: it uses the query range as the random seed.

**Comment by ekg** [comment]
This is ideal! Thank you.
